- java/com/google/re2j/Matcher.java
- javatests/com/google/re2j/MatcherTest.java
> Stop appendReplacement from throwing an exception when a replacement group is null.

- java/com/google/re2j/Parser.java
The original Go code reads:
g := posixGroup[name]
if g.sign == 0 { ... }
The condition is true if the map lookup failed; there are no actual map values for which sign != 0.
> fix condition incorrectly ported from Go

- java/com/google/re2j/Pattern.java
- java/com/google/re2j/RE2.java
This showed in the profile as a big time consumer. I initially removed
the whole pooling and it was 30% faster.
I tested the memory footprint and was 5 extra allocations per op:
1 for Machine, 2 for Queue, and 2 for Queue.Entry.
So instead I used a ThreadLocal of Machine. This is the same
optimization that Teradata fork does: https://github.com/Teradata/re2j
I also removed the reset method since it is not used and doesn't make
sense after this change.
> Use a ThreadLocal instead a synchronization mechanism

- java/com/google/re2j/Pattern.java
- java/com/google/re2j/RE2.java
This method was part of the Pattern API.
Now it doesn't clean all the threds but just the current thread,
since the ThreadLocal doesn't allow us to access the rest of
threads.
> Restore Pattern.reset() method

- java/com/google/re2j/Matcher.java
- javatests/com/google/re2j/MatcherTest.java
Add appendReplacement and appendTail methods that accept StringBuilders.
StringBuffer performs synchronization that is rarely necessary and has
performance overhead.
This change mirrors additions to java.util.regex.Matcher made in JDK 9:
https://bugs.openjdk.java.net/browse/JDK-8039124
> Add StringBuilder overloads of Matcher methods

- java/com/google/re2j/Pattern.java
- java/com/google/re2j/RE2.java
This change rollsback 3def69665, 7597ac7e5cf and f6ab6e0b99 due to an
internal (Google) memory regression.
The cause is a memory leak because of a non-static ThreadLocal usage that contained references to the object instance itself (Machine -> RE2 objects).
The main issue is creating unbound new ThreadLocal instances leaks ThreadLocals since they are not GCed.
The repro case is much easier:
```
public class Main {
public static void main(String[] args) {
for (int i = 0; i < 10000000; i++) {
Pattern.compile("aaaa").matches("aaaa");
}
}
}
```
What is happening here?
Each Pattern.compile is creating a new RE2 instance. Each RE2 instance is creating its own ThreadLocal.
When we use the ThreadLocal we access a per thread map ThreadLocalMap. This map contains Entries with ThreadLocal as key and …
> Rollback of ThreadLocal optimization change

- build.gradle
On my machine, this reduces a clean build and check from 29s to 19s.
> Allow parallel execution of tests.

- java/com/google/re2j/Parser.java
- javatests/com/google/re2j/RE2CompileTest.java
Previously, the parser would unconditionally attempt to read the unicode
class spec after a \p or \P, even if the pattern is truncated and
invalid.
Fixes issue #72.
> Detect invalid unicode class specification

- build.gradle
Unfortunately, IntelliJ ignores the `exclude` directive in the source
set declaration and needs to be told about this separately.
> Mark GWT super sources as excluded

- java/com/google/re2j/Regexp.java
- javatests/com/google/re2j/RegexpHashcodeEqualsTest.java
Fixes warning about equals() being implemented without hashCode().
> Add Regexp.hashCode and tests.

- javatests/com/google/re2j/GWTTest.java
- testdata/com/google/re2j/RE2J-Fake.gwt.xml
This caused errors in some GWT applications, and GWTTest passes without it.
> Use a separate fake GWT module with the entry point.

- java/com/google/re2j/RE2.java
This change attempts to reduce monitor contention.
> Don't create Machine while holding this' monitor.

- README.md
- java/com/google/re2j/Matcher.java
- java/com/google/re2j/Parser.java
- java/com/google/re2j/RE2.java
- java/com/google/re2j/Regexp.java
- javatests/com/google/re2j/MatcherTest.java
- javatests/com/google/re2j/ParserTest.java
This changes the parser to annotate the returned Regexp with information
about named capture groups. During compliation, this information is
passed along to the RE2 instance and thence to the Matcher.
> Named group support.

- build.gradle
Tested by running `gradle jar` and verifying that RE2J.gwt.xml is included.
> Include the RE2J.gwt.xml file in the release jar

- build.gradle
Tested by running `gradle jar` and verifying that the sources are included.
> Add supersourced files and RE2J.gwt.xml to the source jar instead of the binary jar

- README.md
- build.gradle
Updated bintray plugin version to 1.8.1, release wouldn't succeed
without it.
Fixed an issue where we had two release name variables for some reason.
> Release version 1.3

- .travis.yml
Gradle no longer works with Java 7 without workaround flags, and it's
probably time to move on from Java 7 anyway.
> Drop Travis checks for Java 7

- README.md
Fix link of "latest release tag", because link is old version of re2j.
Because in github tag page, latest release is displayed in release page,
So It is good enogth that write link to release page, I think.
> Fix link of latest release tag is old.

- java/com/google/re2j/Parser.java
- javatests/com/google/re2j/ParserTest.java
Previously, the parser was unconditionally pop()ing two chars without
checking if the second was available.
Fixes https://github.com/google/re2j/issues/103.
> Fix handling of truncated two-digit hex escapes

- java/com/google/re2j/Parser.java
- javatests/com/google/re2j/ParserTest.java
Ports the fix of https://github.com/golang/go/issues/11187 to RE2/J. The
contents of a \Q...\E sequence is now treated as a sequence of literal
chars, not a single literal string.
Fixes https://github.com/google/re2j/issues/92.
> Fix treatment of \Q\E*

- java/com/google/re2j/Parser.java
- javatests/com/google/re2j/ParserTest.java
- javatests/com/google/re2j/PatternTest.java
In the past, `a.*?c|a.*?b` was factored to `a.*?[bc]`. Thus, given
"abc" as its input string, the automaton would consume "ab" and
then stop (when unanchored) whereas it should consume all of "abc"
as per leftmost semantics.
This fix is ported from Go's regex impl,
https://go-review.googlesource.com/c/go/+/18357/.
Fixes https://github.com/google/re2j/issues/93.
> fix factoring of common prefixes in alternations

- .travis.yml
.travis.yml was still configured to cache maven artifacts, but we use
gradle now
> enable caching of gradle artifacts

- java/com/google/re2j/Machine.java
- java/com/google/re2j/MachineInput.java
- javatests/com/google/re2j/MatcherTest.java
This change makes `RE2.match(CharSequence input, int start, int end,
...)` treat `input` as extending from `(0, input.size()]` for the
purpose of zero-width assertions. Previously, `input` was considered to
extend from `(start, end]`.
This is required when evaluating capturing groups. RE2/J re-matches the
capturing group within a previous successful match, e.g.
```
Matcher m = Pattern.compile("(he)llo").matcher("hello world");
m.find() -> true
m.group(0) -> "hello"
m.group(1) -> "he"
```
During the evaluation of the last statement, RE2/J re-evaluates the
pattern within group(0) (i.e. "hello"). Before this change, RE2/J would
consider the position after 'o' and before 'w' to be both end-of-text
and end-of-line. This would cause zero-width matchers (e.g. $) to
incorrectly match, generating …
> Fix zero-width assertions in capture group eval

- README.md
- build.gradle
See issue #112, this will allow Debian package maintainers to use a
clean version of re2j rather than a commit hash.
> move RE2/J to version 1.5, allows for Debian packaging

- build.gradle
This prevents users from having to update every header whenever the year
changes.
> skip existing headers in license check

- benchmarks/src/main/java/com/google/re2j/benchmark/BenchmarkFullMatch.java
- benchmarks/src/main/java/com/google/re2j/benchmark/BenchmarkSubMatch.java
- benchmarks/src/main/java/com/google/re2j/benchmark/Implementations.java
- java/com/google/re2j/Matcher.java
- java/com/google/re2j/MatcherInput.java
- java/com/google/re2j/Pattern.java
- java/com/google/re2j/RE2.java
- javatests/com/google/re2j/ApiTestUtils.java
- javatests/com/google/re2j/MatcherTest.java
- javatests/com/google/re2j/RE2Test.java
Summary:
1. Introduce MatcherInput to represent both utf16 and utf8.
2. Reuse existing tests with ApiTestUtils to use both MatcherInput.
3. Updated some benchmark to use binary. Didn't find any meaningful difference.
Closes https://github.com/google/re2j/issues/84
> Support matching binary utf8 bytes

- build.gradle
- java/com/google/re2j/Machine.java
- java/com/google/re2j/RE2.java
The locking could be avoided entirely by allocating wrapper objects for the stack nodes, but I'm not sure if that's desirable. I've also provided another approach that is more complex but offers lock-freedom when the cache is empty.
> Avoid locking for put methods for RE2. Fixes #46

- java/com/google/re2j/Parser.java
- javatests/com/google/re2j/PatternTest.java
Previously, the parser would match each individual character within a
\Q...\E section. Runes requiring a surrogate pair would be incorrectly
treated as two individual characters.
E.g.
String source = new StringBuilder().appendCodePoint(110781).toString();
Before this change:
Parser.parse(source, ...) matches \x{1b0bd}
Parser.parse("\\Q" + source + "\\E", ...) matches \x{d82c}\x{dcbd}
After this change:
Parser.parse(source, ...) matches \x{1b0bd}
Parser.parse("\\Q" + source + "\\E", ...) matches \x{1b0bd}
Fixes https://github.com/google/re2j/issues/123.
> Fix quoting of codepoints requiring surrogate pairs.

- java/com/google/re2j/RE2.java
This avoids the unnecessary more complicated path that resolves the
charset by name.
> Replaces String.getBytes("UTF") with getBytes(StandardCharsets.UTF_8)

- java/com/google/re2j/RE2.java
Reverts google/re2j#145 to keep re2j Android API level 14 compatible.
> Revert "Replaces String.getBytes("UTF") with getBytes(StandardCharsets.UTF_8)"

- benchmarks/src/main/java/com/google/re2j/benchmark/BenchmarkSplit.java
- benchmarks/src/main/java/com/google/re2j/benchmark/Implementations.java
- java/com/google/re2j/Pattern.java
- javatests/com/google/re2j/PatternTest.java
Omit leading empty matches from Pattern.split, improve performance
Fixes #131.
This change modifies Pattern.split to omit a leading empty match. This
behavior was specified in JDK8 and brings RE2/J split into line with
more recent JDK implementations.
Furthermore, the split function no longer needs determine the number of
matches before assembling the result. The upshot is that the number of
find() calls is halved in many cases. The benchmark in the previous
change shows a significant improvement.
```
Reference impl (JDK):
BenchmarkSplit.benchmarkSplit     JDK  avgt    5  14.217 ± 0.410  us/op
RE2J (before):
BenchmarkSplit.benchmarkSplit    RE2J  avgt    5  95.807 ± 6.737  us/op
RE2J (after):
BenchmarkSplit.benchmarkSplit    RE2J  avgt    5  49.092 ± 0.717  us/op
```
> Improve split

- RELEASING.md
- build.gradle
This change allows RE2J to be released again. I updated the release
instructions, the test of whether they are accurate will be when I do
this process again in a few months!
> Bintray is gone, we now publish directly to Sonatype Nexus

- benchmarks/src/main/java/com/google/re2j/benchmark/BenchmarkCaseInsensitiveSubmatch.java
- benchmarks/src/main/java/com/google/re2j/benchmark/BenchmarkSubMatch.java
- benchmarks/src/main/java/com/google/re2j/benchmark/BenchmarkUtils.java
- benchmarks/src/main/java/com/google/re2j/benchmark/Implementations.java
- benchmarks/src/main/resources/unicode-sample-text.txt
- java/com/google/re2j/Inst.java
- java/com/google/re2j/Unicode.java
- javatests/com/google/re2j/UnicodeTest.java
One of our production services uses re2j to match several hundred mostly
case-insensitive patterns of varying complexity against text.
We observed that approximately 12% of CPU time was being spent in
toLowerCase() as called from simpleFold(), due to the necessity of doing
at least one character data lookup per Inst.Rune in the common case that
the input rune being examined did not match the instruction.
As a fix, implement a method equalsIgnoreCase() that performs
Unicode-aware case-insensitive comparison between two runes, with a fast
path for the common case where both input runes are ASCII, and use it in
Inst for single-rune case-insensitive comparison. This takes character
data lookups out of the hot path.
The existing re2j benchmarks did not exercise case-insensitive patterns,
so …
> Add fast path for ASCII case folding

- java/com/google/re2j/Inst.java
- java/com/google/re2j/Unicode.java
dc7d6e5d41225dc0825ea6fe4c6055ff854abe13 unfortunately increases the
incidence of infinite loops during case folding if re2j is running on a
JVM newer than the version used to generate the bundled
UnicodeTables.java and the input contains a rune that would require
special case folding rules to form a closed fold loop. \u1C80 (Cyrillic
Small Letter Rounded Ve) is an example of such a rune.
Workaround the issue by inverting the order of parameters passed to
equalsIgnoreCase() so that the rune from the pattern being matched,
rather than the input content, undergoes case folding instead. This does
not fully eliminate the possibility of an infinite loop in this
scenario, since the pattern may well contain one of the problematic
runes, but it effectively restores the situation as it was pre …
> Reduce the incidence of infinite loops while case folding

- java/com/google/re2j/Matcher.java
Use an explicit "UTF-8" character set argument when creating Strings from bytes. The platform default character set is guaranteed to be UTF-8.
> Use an explicit "UTF-8" character set argument when creating Strings from bytes. The platform default character set is guaranteed to be UTF-8.

- java/com/google/re2j/Matcher.java
- java/com/google/re2j/Pattern.java
- java/com/google/re2j/RE2.java
- javatests/com/google/re2j/ApiTestUtils.java
- javatests/com/google/re2j/MatcherTest.java
- javatests/com/google/re2j/PatternTest.java
This PR exposes `Pattern.programSize()` and `Matcher.programSize()` public API.
The program size represents a very approximate measure of a regexp's "cost". Larger numbers are more expensive than smaller numbers.
Similar to the canonical C++ implementation (see [`RE2.ProgramSize()`](https://github.com/google/re2/blob/6dcd83d60f7944926bfd308cc13979fc53dd69ca/re2/re2.h#L326-L328)), re2j will return the program size as the number of instructions of the regex program without making any promises or claims except "larger is more expensive".
Context: The need for this change arose from cross-language projects, such as gRPC and CEL. gRPC needs to configure the maximum size of regex programs in CEL to the same number across all languages. While it's possible in gRPC-Cpp via  CEL-Cpp …
> Add `Pattern.programSize()` and `Matcher.programSize()`
